/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface WebFeatureGeneratorSchema {
  /**
   * The name of the model for this feature.
   */
  model: string
  /**
   * The name of the application you are adding the feature to.
   */
  app?: string
  /**
   * The label field for the model. Generally 'name' or 'title'.
   */
  label?: string
  /**
   * Command separated list of actors to create CRUD for.
   */
  crud?: string
  /**
   * Do not create a data access library for this feature.
   */
  skipDataAccess?: boolean
  /**
   * Do not create a feature library for this feature.
   */
  skipFeature?: boolean
  /**
   * Do not create a ui library for this feature.
   */
  skipUi?: boolean
}
