/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PrismaModelGeneratorSchema {
  /**
   * Name of the model to create.
   */
  name: string
  /**
   * The label field for the model. Generally 'name' or 'title'.
   */
  label?: string
  /**
   * The path to the schema file to add the model to. Defaults to 'prisma/schema.prisma'.
   */
  schemaFile?: string
  /**
   * The field to add to the model, in the format 'name:type'. Use this flag multiple times to add multiple fields.
   */
  fields?: string[]
}
