fragment CollectionDetails on Collection {
  id
  slug
  name
  description
  imageUrl
  token {
    ...NetworkTokenDetails
  }
}

fragment CollectionAssetAttributeDetails on CollectionAssetAttribute {
  key
  value
  count
}

fragment CollectionAssetDetails on CollectionAsset {
  id
  name
  description
  imageUrl
  owner
  attributes {
    ...CollectionAssetAttributeDetails
  }
}

fragment CollectionAssetWithDetailsFragment on CollectionAssetWithDetails {
  id
  name
  description
  imageUrl
  owner
  isCompressed
  jsonMetadataUrl
  onChainCollectionAddress
  royalty
  assetType
  attributes {
    ...CollectionAssetAttributeDetails
  }
}

query userCollectionFindMany($input: UserCollectionFindManyInput!) {
  items: userCollectionFindMany(input: $input) {
    ...CollectionDetails
  }
}

query userCollectionAssetFindMany($input: UserCollectionAssetFindManyInput!) {
  items: userCollectionAssetFindMany(input: $input) {
    ...CollectionAssetDetails
  }
}

query userCollectionFindOne($collectionId: String!) {
  item: userCollectionFindOne(collectionId: $collectionId) {
    ...CollectionDetails
    attributes {
      ...CollectionAssetAttributeDetails
    }
  }
}

query userCollectionAssetFindOne($input: UserCollectionAssetFindOneInput!) {
  item: userCollectionAssetFindOne(input: $input) {
    ...CollectionAssetWithDetailsFragment
  }
}

mutation userCollectionCreate($input: UserCollectionCreateInput!) {
  created: userCollectionCreate(input: $input) {
    ...CollectionDetails
  }
}

mutation userCollectionDelete($collectionId: String!) {
  deleted: userCollectionDelete(collectionId: $collectionId) {
    ...CollectionDetails
  }
}
