/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PrismaSyncGeneratorSchema {
  /**
   * The name of the application to sync
   */
  app?: string
  /**
   * The path to the schema file to sync
   */
  schemaFile?: string
  /**
   * Print more output
   */
  verbose?: boolean
}
