/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ApiCrudGeneratorSchema {
  /**
   * The name of the application you are adding the feature to.
   */
  app: string
  /**
   * The name of the actor you are adding the feature to.
   */
  actor: string
  /**
   * The label field for the model. Generally 'name' or 'title'.
   */
  label?: string
  /**
   * The name of the model for this feature.
   */
  model: string
  /**
   * The id field of the model owner. Generally 'userId' or 'ownerId'.
   */
  modelParentId?: string
  /**
   * The name of the model owner. Generally 'User'.
   */
  modelParent?: string
}
