/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RenameGeneratorSchema {
  /**
   * Don't actually rename files, just print what would be done
   */
  dryRun?: boolean
  /**
   * Don't prompt for confirmation
   */
  quiet?: boolean
  /**
   * Search for this text
   */
  search: string
  /**
   * Replace with this text
   */
  replace?: string
}
